apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-rstudio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistentVolumes/rstudio"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-jupyter-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistentVolumes/jupyter"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-pg-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistentVolumes/pg-pv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-mongodb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/mongodb"