apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-analytics-rstudio-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  volumeName: "project-analytics-rstudio-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-neil-rstudio-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.3Gi
  volumeName: "user-neil-rstudio-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-pg-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  volumeName: "analytics-pg-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-mongodb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  volumeName: "analytics-mongodb-pv"