apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-rstudio-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dev/sda1/analytics"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-jupyter-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dev/sda1/analytics"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-pg-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dev/sda1/analytics"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-mongodb-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dev/sda1/analytics"