apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-local-rstudio-pvc
  labels:
    app: rstudio
spec:
  storageClassName: analytic-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: analytics-local-rstudio-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-local-mongodb-pvc
  labels:
    app: mongodb
spec:
  storageClassName: analytic-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: analytics-local-mongodb-pv