apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-rstudio-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "analytics-rstudio-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-jupyter-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "analytics-jupyter-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-pg-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: "analytics-pg-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-mongodb-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: "analytics-mongodb-pv"