apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firstChart.fullname" . }}
  labels:
    {{- include "firstChart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "firstChart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firstChart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.rstudio.podName }}
          image: "{{ .Values.rstudio.imageRepository }}:{{ .Values.rstudio.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rstudio.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.rstudio.service.rstudioPort }}
          env:
            - name: PASSWORD
              value: "mypass"
            - name: ROOT
              value: "TRUE"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
