apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firstChart.fullname" . }}
  labels:
    {{- include "firstChart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "firstChart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firstChart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firstChart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.rstudio.podName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.rstudio.imageRepository }}:{{ .Values.rstudio.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rstudio.imagePullPolicy }}
          ports:
            - name: rstudio-port
              containerPort: {{ .Values.rstudio.service.rstudioPort }}
              protocol: {{ .Values.rstudio.service.portProtocol }}
          env:
            - name: {{ .Values.rstudio.env.firstEnvName }}
              value: {{ .Values.rstudio.env.firstEnvValue }}
            - name: {{ .Values.rstudio.env.secondEnvName }}
              value: {{ .Values.rstudio.env.secondEnvValue }}
          livenessProbe:
            httpGet:
              path: /
              port: rstudio-port
          readinessProbe:
            httpGet:
              path: /
              port: rstudio-port
          resources:
            {{- toYaml .Values.rstudio.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
