apiVersion: v1
kind: Service
metadata:
  name: {{ include "firstChart.fullname" . }}
  labels:
    {{- include "firstChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
      
  selector:
    {{- include "firstChart.selectorLabels" . | nindent 4 }}


