# This is a place holder for now. 
statefulset:
  enabled: false

# Replica Count
replicaCount: 1

# Specify the deployment strategy. The provided are defaults
deploymentStrategy: {}
  # rollingUpdate:
  #   maxSurge: 25%
  #   maxUnavailable: 25%
  # type: RollingUpdate

# Information for the first image, rstudio
rstudio:
  podName: rstudio-server
  imageRepository: rocker/rstudio
  imageTag: 3.6.3 #4.0.3
  imagePullPolicy: IfNotPresent
  env:
    firstEnvName: PASSWORD
    firstEnvValue: "mypass"
    secondEnvName: ROOT
    secondEnvValue: "TRUE"
  persistentStorage:
    firstVolName: project-a-rstudio-volume
    firstClaimName: project-a-rstudio-pvc
    secondVolName: user-neil-rstudio-volume
    secondClaimName: user-neil-rstudio-pvc
  resources: {}
    # cpu: 250m
    # memory: 4800Mi
  service:
    type: NodePort
    rstudioPort: 8787
    podPort: 30633 #or 8787
    portProtocol: TCP
    # clusterIP: None
  route: {}
    # enabled: false
    # name: docker
    # portName: docker
    # labels:
    # annotations:
 
# Values passed to the dependent postgres chart
postgresql:
  enabled: false
  postgresqlUsername: postgres
  postgresqlPassword: mypass
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: false
    # If an existing pvc exists (created prior to this chart) it can be passed here.
    existingClaim: pg-pvc
    
    ## The path the volume will be mounted at, useful when using different
    ## PostgreSQL images.
    ##
    mountPath: /bitnami/postgresql

    ## The subdirectory of the volume to mount to, useful in dev environments
    ## and one PV for multiple services.
    ##
    subPath: ''

    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    ## selector can be used to match an existing PersistentVolume
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    selector: {}
 

monogodb:
  enabled: true
  auth:
    enabled: true
    rootPassword: ""
  persistence:
    enabled: true
    # Requires mongodb.persistence.enabled: true
    # If defined, PVC must be created manually before the volume will be bound
    # existingClaim: 
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  
  




imagePullSecrets: []
nameOverride: "rstudio"
fullnameOverride: "rstudio"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
