apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-a-rstudio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistentVolumes/project-a-rstudio"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-neil-rstudio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistentVolumes/user-neil-rstudio"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistentVolumes/pg-pv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/mongodb"